apiVersion: v1
kind: Pod
metadata:
        name: restult-app-pod
        labels:
                name: result-app-pod
                app: demo-voting-app
spec:
        containers:
                - name: voting-app
                  image: kodekloud/examplevotingapp_result:v1
                  ports:
                    - containerPort: 80

